version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - '80:80'
  strapi:
    build: ./strapi
    container_name: strapi
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=${DATABASE_CLIENT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./app:/srv/app
    env_file: ./strapi/.env
    ports:
      - '1337:1337'
    depends_on:
      - mongo
    command: 'strapi start'
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    env_file: ./strapi/.env
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    restart: always
  nextjs:
    build: ./frontend
    depends_on:
      - strapi
      - mongo
    ports:
      - '3000:3000'